//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlterTools.BatchExport.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlterTools.BatchExport.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Base_Button_Help_Content {
            get {
                return ResourceManager.GetString("Base.Button.Help.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin usage help.
        /// </summary>
        public static string Base_Button_Help_ToolTip {
            get {
                return ResourceManager.GetString("Base.Button.Help.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Base_Button_Load_Content {
            get {
                return ResourceManager.GetString("Base.Button.Load.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load (.rvt) files.
        /// </summary>
        public static string Base_Button_Load_ToolTip {
            get {
                return ResourceManager.GetString("Base.Button.Load.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files list in (.rvt) format.
        /// </summary>
        public static string Base_ListBox_ToolTip {
            get {
                return ResourceManager.GetString("Base.ListBox.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVT files to be exported.
        /// </summary>
        public static string Detach_Header {
            get {
                return ResourceManager.GetString("Detach.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch export of detached models.
        /// </summary>
        public static string Detach_Title {
            get {
                return ResourceManager.GetString("Detach.Title", resourceCulture);
            }
        }
    }
}
