//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlterTools.BatchExport.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlterTools.BatchExport.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Base_Button_Browse {
            get {
                return ResourceManager.GetString("Base.Button.Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Base_Button_Delete_Content {
            get {
                return ResourceManager.GetString("Base.Button.Delete.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected files from list.
        /// </summary>
        public static string Base_Button_Delete_ToolTip {
            get {
                return ResourceManager.GetString("Base.Button.Delete.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase list.
        /// </summary>
        public static string Base_Button_EraseList {
            get {
                return ResourceManager.GetString("Base.Button.EraseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Base_Button_Help_Content {
            get {
                return ResourceManager.GetString("Base.Button.Help.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin usage help.
        /// </summary>
        public static string Base_Button_Help_ToolTip {
            get {
                return ResourceManager.GetString("Base.Button.Help.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Base_Button_Load_Content {
            get {
                return ResourceManager.GetString("Base.Button.Load.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load (.rvt) files.
        /// </summary>
        public static string Base_Button_Load_ToolTip {
            get {
                return ResourceManager.GetString("Base.Button.Load.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load list.
        /// </summary>
        public static string Base_Button_LoadList_Content {
            get {
                return ResourceManager.GetString("Base.Button.LoadList.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load previously saved configuration file in (.json) format.
        /// </summary>
        public static string Base_Button_LoadList_ToolTip {
            get {
                return ResourceManager.GetString("Base.Button.LoadList.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save list.
        /// </summary>
        public static string Base_Button_SaveList_Content {
            get {
                return ResourceManager.GetString("Base.Button.SaveList.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration file in (.json) format.
        /// </summary>
        public static string Base_Button_SaveList_ToolTip {
            get {
                return ResourceManager.GetString("Base.Button.SaveList.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Base_Button_Start_Content {
            get {
                return ResourceManager.GetString("Base.Button.Start.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start batch export of current configuration.
        /// </summary>
        public static string Base_Button_Start_ToolTip {
            get {
                return ResourceManager.GetString("Base.Button.Start.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export view.
        /// </summary>
        public static string Base_ExportScopeView {
            get {
                return ResourceManager.GetString("Base.ExportScopeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export whole model.
        /// </summary>
        public static string Base_ExportScopeWhole {
            get {
                return ResourceManager.GetString("Base.ExportScopeWhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVT files to be exported.
        /// </summary>
        public static string Base_Header {
            get {
                return ResourceManager.GetString("Base.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore missing view
        ///and export whole project.
        /// </summary>
        public static string Base_IgnoreMissingView {
            get {
                return ResourceManager.GetString("Base.IgnoreMissingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files list in (.rvt) format.
        /// </summary>
        public static string Base_ListBox_ToolTip {
            get {
                return ResourceManager.GetString("Base.ListBox.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postfix.
        /// </summary>
        public static string Base_Postfix {
            get {
                return ResourceManager.GetString("Base.Postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postfix to be added to the end of a file name.
        /// </summary>
        public static string Base_Postfix_ToolTip {
            get {
                return ResourceManager.GetString("Base.Postfix.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Base_Prefix {
            get {
                return ResourceManager.GetString("Base.Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix to be added to the start of a file name.
        /// </summary>
        public static string Base_Prefix_ToolTip {
            get {
                return ResourceManager.GetString("Base.Prefix.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to folder.
        /// </summary>
        public static string Base_ResultingFolder {
            get {
                return ResourceManager.GetString("Base.ResultingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t create log file.
        /// </summary>
        public static string Base_TurnOffLog {
            get {
                return ResourceManager.GetString("Base.TurnOffLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefixes of Worksets to be closed.
        /// </summary>
        public static string Base_WorksetPrefixes {
            get {
                return ResourceManager.GetString("Base.WorksetPrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the Prefixes of all Worksets that need to be closed when opening the file, separated by semicolons (;). 
        ///Worksets with Links are usually closed to speed up the opening of models..
        /// </summary>
        public static string Base_WorksetPrefixes_ToolTip {
            get {
                return ResourceManager.GetString("Base.WorksetPrefixes.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Const_Default {
            get {
                return ResourceManager.GetString("Const.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A difference in coordinate systems has been detected. 
        ///Do you want to retrieve coordinates from the file?.
        /// </summary>
        public static string Const_DiffCoord {
            get {
                return ResourceManager.GetString("Const.DiffCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Const_Error {
            get {
                return ResourceManager.GetString("Const.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Const_Link {
            get {
                return ResourceManager.GetString("Const.Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document doesn&apos;t have any transmission data.
        /// </summary>
        public static string Const_NoTransDataAlert {
            get {
                return ResourceManager.GetString("Const.NoTransDataAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find correct info in the text file.
        /// </summary>
        public static string Const_VMBase_NoFiles {
            get {
                return ResourceManager.GetString("Const.VMBase.NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file scheme.
        /// </summary>
        public static string Const_WrongScheme {
            get {
                return ResourceManager.GetString("Const.WrongScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Detach_Change {
            get {
                return ResourceManager.GetString("Detach.Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check models for “empty” view.
        /// </summary>
        public static string Detach_CheckBox_EmptyView_Content {
            get {
                return ResourceManager.GetString("Detach.CheckBox.EmptyView.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the “View_name” view be checked for the presence of objects, and if the view is empty, the file will be saved with the prefix “EMPTY_”.
        /// </summary>
        public static string Detach_CheckBox_EmptyView_ToolTip {
            get {
                return ResourceManager.GetString("Detach.CheckBox.EmptyView.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge models.
        /// </summary>
        public static string Detach_CheckBox_Purge_Content {
            get {
                return ResourceManager.GetString("Detach.CheckBox.Purge.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implements the functionality of the &quot;Purge unused&quot; command until complete cleanup (several times).
        /// </summary>
        public static string Detach_CheckBox_Purge_ToolTip {
            get {
                return ResourceManager.GetString("Detach.CheckBox.Purge.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        public static string Detach_Mask {
            get {
                return ResourceManager.GetString("Detach.Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05_WIP.
        /// </summary>
        public static string Detach_MaskIn {
            get {
                return ResourceManager.GetString("Detach.MaskIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06_Common.
        /// </summary>
        public static string Detach_MaskOut {
            get {
                return ResourceManager.GetString("Detach.MaskOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Links.
        /// </summary>
        public static string Detach_RemoveLinks {
            get {
                return ResourceManager.GetString("Detach.RemoveLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove empty worksets.
        /// </summary>
        public static string Detach_RemoveWorksets {
            get {
                return ResourceManager.GetString("Detach.RemoveWorksets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename files.
        /// </summary>
        public static string Detach_Rename {
            get {
                return ResourceManager.GetString("Detach.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch export of detached models.
        /// </summary>
        public static string Detach_Title {
            get {
                return ResourceManager.GetString("Detach.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Detach_To {
            get {
                return ResourceManager.GetString("Detach.To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the view to check.
        /// </summary>
        public static string Detach_ViewName {
            get {
                return ResourceManager.GetString("Detach.ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export base quantities.
        /// </summary>
        public static string IFC_BaseQuantities {
            get {
                return ResourceManager.GetString("IFC.BaseQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Walls, Columns,
        ///Ducts by Level.
        /// </summary>
        public static string IFC_CheckBox_Splitting {
            get {
                return ResourceManager.GetString("IFC.CheckBox.Splitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export parameter mapping table.
        /// </summary>
        public static string IFC_MappingTable {
            get {
                return ResourceManager.GetString("IFC.MappingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space boundaries.
        /// </summary>
        public static string IFC_SpaceBoundaries {
            get {
                return ResourceManager.GetString("IFC.SpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string IFC_SpaceBoundaryLevels0 {
            get {
                return ResourceManager.GetString("IFC.SpaceBoundaryLevels0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Level.
        /// </summary>
        public static string IFC_SpaceBoundaryLevels1 {
            get {
                return ResourceManager.GetString("IFC.SpaceBoundaryLevels1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Level.
        /// </summary>
        public static string IFC_SpaceBoundaryLevels2 {
            get {
                return ResourceManager.GetString("IFC.SpaceBoundaryLevels2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC batch export.
        /// </summary>
        public static string IFC_Title {
            get {
                return ResourceManager.GetString("IFC.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC version.
        /// </summary>
        public static string IFC_Version {
            get {
                return ResourceManager.GetString("IFC.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to the current Workset.
        /// </summary>
        public static string Link_CurrentWorkset {
            get {
                return ResourceManager.GetString("Link.CurrentWorkset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of RVT files to link.
        /// </summary>
        public static string Link_Header {
            get {
                return ResourceManager.GetString("Link.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Links.
        /// </summary>
        public static string Link_Pin {
            get {
                return ResourceManager.GetString("Link.Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch link models.
        /// </summary>
        public static string Link_Title {
            get {
                return ResourceManager.GetString("Link.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load config.
        /// </summary>
        public static string Migrate_Button_LoadConfig {
            get {
                return ResourceManager.GetString("Migrate.Button.LoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch migrate models.
        /// </summary>
        public static string Migrate_Title {
            get {
                return ResourceManager.GetString("Migrate.Title", resourceCulture);
            }
        }
    }
}
